# Generated by Django 4.1.10 on 2023-10-15 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_datos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='apellido_M',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='apellido_P',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='apellido_M',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='apellido_P',
        ),
    ]
