# Generated by Django 5.0 on 2023-12-30 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_de_datos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprasrealizadas',
            name='id_carrito',
        ),
        migrations.CreateModel(
            name='ComprasRealizadas_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprasRealizadas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_datos.comprasrealizadas')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_de_datos.productos')),
            ],
        ),
    ]
